POST http://localhost:8080/api/nacos/login
Content-Type: application/json

{
}

###
GET http://localhost:8080/api/nacos/namespaces

###
GET http://localhost:8080/api/nacos/configs?namespaceId=da536c77-40f2-48e0-b475-8da7b2fd0cdd

###
GET http://localhost:8080/api/nacos/services?namespaceId=da536c77-40f2-48e0-b475-8da7b2fd0cdd

###
GET http://localhost:8080/api/nacos/instances?namespaceId=da536c77-40f2-48e0-b475-8da7b2fd0cdd&serviceName=video-event&
    groupName=DEFAULT_GROUP

###
POST http://localhost:8080/api/k8s/login
Content-Type: application/json

{
}

###
GET http://localhost:8080/api/k8s/namespaces

###
GET http://localhost:8080/api/k8s/namespaces/video-platform/deployments

###
GET http://localhost:8080/api/k8s/namespaces/video-platform/deployments/common-web/pods

###
POST http://localhost:8080/api/k8s/exec
Content-Type: application/json

{
  "namespace": "video-platform",
  "pod": "video-event-5b657fd654-8knfj",
  "container": "video-event",
  "command": [
    "ls"
  ]
}

###
POST https://10.43.86.32:6443/kapis/iam.kubesphere.io/v1alpha2/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1qaz!QAz"
}

###
GET http://localhost:8080/api/k8s/namespaces/video-platform/services

###
GET http://localhost:28402

